apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
spec:
  selector:
    matchLabels:
      app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "apurvbidkar@gmail.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "root"
        - name: PGADMIN_LISTEN_ADDRESS
          value: "0.0.0.0"
        ports:
        - containerPort: 80
      - name: pgadmin
        image: dpage/pgadmin4:latest
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "apurvbidkar22@gmail.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "user"
        - name: PGADMIN_LISTEN_ADDRESS
          value: "0.0.0.0"
        ports:
        - containerPort: 80